version: '3.3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: oop_db_1
      # So you don't have to use root, but you can if you like
      MYSQL_USER: root
      # You can use whatever password you like
      MYSQL_PASSWORD: link
      # Password for root access
      MYSQL_ROOT_PASSWORD: root
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    
      # Opens port 3306 on the container
      
      # Where our data will be persisted
    volumes:
      - my-db:/mysql
      
  oop-server:
    image: openjdk:11
    ports:
    - 1234:8080
    build: .
    command: java -jar jar_name.jar
# Names our volume
volumes:
  my-db:
  
